/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagestiongimnasio.Jframe;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis LB
 */
public class LoginJframe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginJframe.class.getName());

    /**
     * Creates new form LoginJframe
     */
    public LoginJframe() {
        initComponents();
        
        lblMensajeError.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarLogin = new javax.swing.JButton();
        lblLoginLogo = new javax.swing.JLabel();
        lblMensajeError = new javax.swing.JLabel();
        txtIngresaPassword = new javax.swing.JTextField();
        pssCasillaContrasenia = new javax.swing.JPasswordField();
        btnValidarLogin = new javax.swing.JButton();
        cbxMostrarContrasenia = new javax.swing.JCheckBox();
        lblColorFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarLogin.setForeground(new java.awt.Color(0, 118, 221));
        btnCerrarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestiongimnasio/imagenesjframe/close.png"))); // NOI18N
        btnCerrarLogin.addActionListener(this::btnCerrarLoginActionPerformed);
        getContentPane().add(btnCerrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        lblLoginLogo.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        lblLoginLogo.setForeground(new java.awt.Color(0, 118, 221));
        lblLoginLogo.setText("LOGIN");
        getContentPane().add(lblLoginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        lblMensajeError.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblMensajeError.setForeground(new java.awt.Color(255, 0, 0));
        lblMensajeError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestiongimnasio/imagenesjframe/close.png"))); // NOI18N
        lblMensajeError.setText("Son incorrecto usuario o password");
        getContentPane().add(lblMensajeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        txtIngresaPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIngresaPassword.setForeground(new java.awt.Color(0, 118, 221));
        txtIngresaPassword.setText("Ingresa Usuario");
        txtIngresaPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIngresaPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIngresaPasswordFocusLost(evt);
            }
        });
        getContentPane().add(txtIngresaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 303, -1));

        pssCasillaContrasenia.setForeground(new java.awt.Color(0, 118, 221));
        pssCasillaContrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pssCasillaContraseniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pssCasillaContraseniaFocusLost(evt);
            }
        });
        getContentPane().add(pssCasillaContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 303, -1));

        btnValidarLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnValidarLogin.setForeground(new java.awt.Color(0, 118, 221));
        btnValidarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestiongimnasio/imagenesjframe/login.png"))); // NOI18N
        btnValidarLogin.setText("Login");
        btnValidarLogin.addActionListener(this::btnValidarLoginActionPerformed);
        getContentPane().add(btnValidarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, -1, -1));

        cbxMostrarContrasenia.setForeground(new java.awt.Color(0, 118, 221));
        cbxMostrarContrasenia.setText("Mostrar contraseña");
        cbxMostrarContrasenia.addActionListener(this::cbxMostrarContraseniaActionPerformed);
        getContentPane().add(cbxMostrarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, -1, -1));

        lblColorFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestiongimnasio/imagenesjframe/login background.PNG"))); // NOI18N
        lblColorFondo.setText("jLabel3");
        getContentPane().add(lblColorFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarLoginActionPerformed
        
        int a = JOptionPane.showConfirmDialog(null, "Realmente deseas salir del programa" , "Selecciona", JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnCerrarLoginActionPerformed

    private void txtIngresaPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIngresaPasswordFocusGained

        lblMensajeError.setVisible(false);
        if(txtIngresaPassword.getText().equals("Ingresa Usuario"))
        {
        
            txtIngresaPassword.setText("");
            txtIngresaPassword.setForeground(new Color(0,118,221));
        
        }


        
    }//GEN-LAST:event_txtIngresaPasswordFocusGained

    private void txtIngresaPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIngresaPasswordFocusLost
        
        lblMensajeError.setVisible(false);
        if(txtIngresaPassword.getText().equals(""))
        {
        
            txtIngresaPassword.setText("Ingresa Usuario");
            txtIngresaPassword.setForeground(new Color(0,118,221));
        }
        
    }//GEN-LAST:event_txtIngresaPasswordFocusLost

    private void pssCasillaContraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pssCasillaContraseniaFocusGained
        
        lblMensajeError.setVisible(false);
        if(pssCasillaContrasenia.getText().equals("Ingresa Usuario"))
        {
        
            pssCasillaContrasenia.setText("");
            pssCasillaContrasenia.setForeground(new Color(0,118,221));
        
        }
    }//GEN-LAST:event_pssCasillaContraseniaFocusGained

    private void pssCasillaContraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pssCasillaContraseniaFocusLost
        
        lblMensajeError.setVisible(false);
        if(pssCasillaContrasenia.getText().equals("Ingresa Usuario"))
        {
        
            pssCasillaContrasenia.setText("");
            pssCasillaContrasenia.setForeground(new Color(0,118,221));
        
        }
        
        
    }//GEN-LAST:event_pssCasillaContraseniaFocusLost

    private void btnValidarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarLoginActionPerformed
       
        if(txtIngresaPassword.getText().equals("gms") && pssCasillaContrasenia.getText().equals("admin"))
        {
            setVisible(false);
            new BienvenidaJframe().setVisible(true);
        } else lblMensajeError.setVisible(true);
        
    }//GEN-LAST:event_btnValidarLoginActionPerformed

    private void cbxMostrarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMostrarContraseniaActionPerformed
        
        if(cbxMostrarContrasenia.isSelected())
        {
        
        pssCasillaContrasenia.setEchoChar((char)0);
            
        } else
        {
        
            pssCasillaContrasenia.setEchoChar('*');
        
        }
        
    }//GEN-LAST:event_cbxMostrarContraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginJframe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarLogin;
    private javax.swing.JButton btnValidarLogin;
    private javax.swing.JCheckBox cbxMostrarContrasenia;
    private javax.swing.JLabel lblColorFondo;
    private javax.swing.JLabel lblLoginLogo;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JPasswordField pssCasillaContrasenia;
    private javax.swing.JTextField txtIngresaPassword;
    // End of variables declaration//GEN-END:variables
}
